apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: opa-policy
spec:
  type: middleware.http.opa
  version: v1
  metadata:
    - name: includedHeaders
      value: "authorization"
    - name: defaultStatus
      value: 403
    - name: readBody
      value: "false"
    - name: rego
      value: |
        package http

        import future.keywords.if

        # By default, deny requests
        default allow := false

        # Allow requests if claims are valid.
        # See https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validate-tokens
        allow if claims.appid == "693b7bfc-1128-4245-92e0-7abb1d51c3ca"

        claims := payload {
            v := input.request.headers["Authorization"]
            startswith(v, "Bearer ")
            t := substring(v, count("Bearer "), -1)
            [_, payload, _] := io.jwt.decode(t)
        }
